name: test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            generator: CodeBlocks - Unix Makefiles
            test_excutor: ctest
          - os: macos-latest
            generator: CodeBlocks - Unix Makefiles
            test_excutor: ctest
          - os: windows-latest
            generator: Visual Studio 16 2019
            test_excutor: ctest -C Debug
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: cmake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -G "${{matrix.generator}}"
      - name: build
        run: cmake --build build --target --parallel 10
      - name: test
        run: cd build; ${{matrix.test_excutor}} -V
