name: test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            generator: CodeBlocks - Unix Makefiles
            test_excutor: ctest
            conan_bin_path: /home/runner/.local/bin
          - os: macos-latest
            generator: CodeBlocks - Unix Makefiles
            test_excutor: ctest
            conan_bin_path: /Users/runner/.local/bin
          - os: windows-latest
            generator: Visual Studio 16 2019
            test_excutor: ctest -C Debug
            conan_bin_path: /home/runner/.local/bin
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - name: Setup conan
        run: | 
          echo "::add-path::${{matrix.conan_bin_path}}"
          pip install --user conan
          which conan
      - name: cmake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -G "${{matrix.generator}}"
      - name: build
        run: cmake --build build --target --parallel 10
      - name: test
        run: cd build; ${{matrix.test_excutor}} -V
